/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class RankingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'rankPosition', 'score', 'siteId', 'updatedAt'] as const
  $columns = RankingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rankPosition: number | null
  @column()
  declare score: number | null
  @column()
  declare siteId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SiteMetricSchema extends BaseModel {
  static $columns = ['createdAt', 'dailyVisits', 'id', 'score', 'seoScore', 'siteId', 'speedScore', 'updatedAt', 'uptime'] as const
  $columns = SiteMetricSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dailyVisits: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare score: number | null
  @column()
  declare seoScore: number | null
  @column()
  declare siteId: number | null
  @column()
  declare speedScore: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uptime: number | null
}

export class SiteSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isActive', 'logo', 'name', 'updatedAt', 'url'] as const
  $columns = SiteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare logo: string | null
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string | null
}
